# HotM Installer Testing Framework - Common Utilities
# Shared utilities for all test suites

# Global test configuration
$Script:TestConfig = @{}
$Script:TestMetrics = @{}
$Script:TestArtifacts = @()

function Write-TestLog {
    <#
    .SYNOPSIS
    Writes standardized test log messages with timestamps and categorization.
    
    .PARAMETER Message
    The log message to write.
    
    .PARAMETER Level
    The log level: DEBUG, INFO, WARN, ERROR, SUCCESS.
    
    .PARAMETER Category
    The test category for organization.
    
    .PARAMETER NoConsole
    Skip console output (file only).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Message,
        
        [Parameter(Mandatory = $false)]
        [ValidateSet("DEBUG", "INFO", "WARN", "ERROR", "SUCCESS")]
        [string]$Level = "INFO",
        
        [Parameter(Mandatory = $false)]
        [string]$Category = "GENERAL",
        
        [switch]$NoConsole
    )
    
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss.fff"
    $logMessage = "[$timestamp] [$Level] [$Category] $Message"
    
    # Console output with colors
    if (-not $NoConsole) {
        $color = switch ($Level) {
            "DEBUG" { "Gray" }
            "INFO" { "White" }
            "WARN" { "Yellow" }
            "ERROR" { "Red" }
            "SUCCESS" { "Green" }
            default { "White" }
        }
        
        Write-Host $logMessage -ForegroundColor $color
    }
    
    # File logging
    $logFile = Get-TestLogPath
    if ($logFile) {
        try {
            Add-Content -Path $logFile -Value $logMessage -Encoding UTF8
        } catch {
            # Ignore file logging errors
        }
    }
    
    # Windows Event Log (if available)
    try {
        $eventType = switch ($Level) {
            "ERROR" { "Error" }
            "WARN" { "Warning" }
            default { "Information" }
        }
        
        Write-EventLog -LogName Application -Source "HotM-Installer-Tests" -EventID 1000 -EntryType $eventType -Message $logMessage -ErrorAction SilentlyContinue
    } catch {
        # Event log not available - ignore
    }
}

function Get-TestLogPath {
    <#
    .SYNOPSIS
    Gets the path for the test log file.
    #>
    if ($Script:OutputPath) {
        $logDir = Join-Path $Script:OutputPath "logs"
        if (-not (Test-Path $logDir)) {
            New-Item -ItemType Directory -Path $logDir -Force | Out-Null
        }
        return Join-Path $logDir "installer-tests.log"
    }
    return $null
}

function New-TestResult {
    <#
    .SYNOPSIS
    Creates a standardized test result object.
    
    .PARAMETER TestName
    Name of the test.
    
    .PARAMETER Category
    Test category.
    
    .PARAMETER Status
    Test result status: Pass, Fail, Skip, Warning, Error.
    
    .PARAMETER Message
    Result message or details.
    
    .PARAMETER Duration
    Test execution duration.
    
    .PARAMETER ErrorDetails
    Detailed error information if applicable.
    
    .PARAMETER Artifacts
    Array of artifacts (files, screenshots, etc.) generated by the test.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$TestName,
        
        [Parameter(Mandatory = $true)]
        [string]$Category,
        
        [Parameter(Mandatory = $true)]
        [ValidateSet("Pass", "Fail", "Skip", "Warning", "Error")]
        [string]$Status,
        
        [Parameter(Mandatory = $false)]
        [string]$Message = "",
        
        [Parameter(Mandatory = $false)]
        [TimeSpan]$Duration = [TimeSpan]::Zero,
        
        [Parameter(Mandatory = $false)]
        [string]$ErrorDetails = "",
        
        [Parameter(Mandatory = $false)]
        [array]$Artifacts = @(),
        
        [Parameter(Mandatory = $false)]
        [hashtable]$Metrics = @{}
    )
    
    return [PSCustomObject]@{
        TestName = $TestName
        Category = $Category
        Status = $Status
        Message = $Message
        Duration = $Duration
        ErrorDetails = $ErrorDetails
        Artifacts = $Artifacts
        Metrics = $Metrics
        Timestamp = Get-Date
        Environment = Get-TestEnvironmentSnapshot
    }
}

function Get-TestEnvironmentSnapshot {
    <#
    .SYNOPSIS
    Captures a snapshot of the current test environment.
    #>
    return @{
        OSVersion = (Get-WmiObject Win32_OperatingSystem).Version
        PowerShellVersion = $PSVersionTable.PSVersion.ToString()
        CurrentUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
        MachineName = $env:COMPUTERNAME
        ProcessId = $PID
        WorkingDirectory = (Get-Location).Path
    }
}

function Invoke-TestWithTimeout {
    <#
    .SYNOPSIS
    Executes a test script block with timeout handling.
    
    .PARAMETER ScriptBlock
    The test code to execute.
    
    .PARAMETER TimeoutSeconds
    Maximum execution time in seconds.
    
    .PARAMETER TestName
    Name of the test for logging.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [ScriptBlock]$ScriptBlock,
        
        [Parameter(Mandatory = $false)]
        [int]$TimeoutSeconds = 300,
        
        [Parameter(Mandatory = $false)]
        [string]$TestName = "Unknown"
    )
    
    $job = Start-Job -ScriptBlock $ScriptBlock
    
    try {
        $result = $job | Wait-Job -Timeout $TimeoutSeconds
        
        if ($result) {
            return $job | Receive-Job
        } else {
            $job | Stop-Job
            throw "Test '$TestName' timed out after $TimeoutSeconds seconds"
        }
    } finally {
        $job | Remove-Job -Force -ErrorAction SilentlyContinue
    }
}

function Test-ServiceRunning {
    <#
    .SYNOPSIS
    Tests if a Windows service is running.
    
    .PARAMETER ServiceName
    Name of the service to check.
    
    .PARAMETER TimeoutSeconds
    How long to wait for the service to be running.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$ServiceName,
        
        [Parameter(Mandatory = $false)]
        [int]$TimeoutSeconds = 30
    )
    
    $timeout = [datetime]::Now.AddSeconds($TimeoutSeconds)
    
    do {
        try {
            $service = Get-Service -Name $ServiceName -ErrorAction SilentlyContinue
            if ($service -and $service.Status -eq "Running") {
                return $true
            }
        } catch {
            # Service not found or other error
        }
        
        Start-Sleep -Milliseconds 500
    } while ([datetime]::Now -lt $timeout)
    
    return $false
}

function Test-PortListening {
    <#
    .SYNOPSIS
    Tests if a TCP port is listening and accepting connections.
    
    .PARAMETER Port
    The port number to test.
    
    .PARAMETER HostName
    The hostname or IP address to test (default: localhost).
    
    .PARAMETER TimeoutSeconds
    Connection timeout in seconds.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [int]$Port,
        
        [Parameter(Mandatory = $false)]
        [string]$HostName = "localhost",
        
        [Parameter(Mandatory = $false)]
        [int]$TimeoutSeconds = 10
    )
    
    try {
        $tcpClient = New-Object System.Net.Sockets.TcpClient
        $connectTask = $tcpClient.BeginConnect($HostName, $Port, $null, $null)
        $waitResult = $connectTask.AsyncWaitHandle.WaitOne($TimeoutSeconds * 1000, $false)
        
        if ($waitResult) {
            try {
                $tcpClient.EndConnect($connectTask)
                $result = $tcpClient.Connected
            } catch {
                $result = $false
            }
        } else {
            $result = $false
        }
        
        $tcpClient.Close()
        return $result
        
    } catch {
        return $false
    }
}

function Test-HttpEndpoint {
    <#
    .SYNOPSIS
    Tests if an HTTP endpoint is responding.
    
    .PARAMETER Uri
    The HTTP URI to test.
    
    .PARAMETER ExpectedStatusCode
    Expected HTTP status code (default: 200).
    
    .PARAMETER TimeoutSeconds
    Request timeout in seconds.
    
    .PARAMETER RetryAttempts
    Number of retry attempts.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Uri,
        
        [Parameter(Mandatory = $false)]
        [int]$ExpectedStatusCode = 200,
        
        [Parameter(Mandatory = $false)]
        [int]$TimeoutSeconds = 30,
        
        [Parameter(Mandatory = $false)]
        [int]$RetryAttempts = 3
    )
    
    $attempt = 0
    
    do {
        $attempt++
        
        try {
            $response = Invoke-WebRequest -Uri $Uri -TimeoutSec $TimeoutSeconds -UseBasicParsing -ErrorAction Stop
            
            if ($response.StatusCode -eq $ExpectedStatusCode) {
                return @{
                    Success = $true
                    StatusCode = $response.StatusCode
                    ResponseTime = $null  # TODO: Add response time measurement
                    Content = $response.Content
                }
            } else {
                Write-TestLog "HTTP endpoint returned unexpected status code: $($response.StatusCode)" "WARN" "HTTP"
            }
            
        } catch {
            Write-TestLog "HTTP endpoint test failed (attempt $attempt/$RetryAttempts): $($_.Exception.Message)" "WARN" "HTTP"
            
            if ($attempt -lt $RetryAttempts) {
                Start-Sleep -Seconds 2
            }
        }
        
    } while ($attempt -lt $RetryAttempts)
    
    return @{
        Success = $false
        StatusCode = $null
        ResponseTime = $null
        Content = $null
        Error = "Failed after $RetryAttempts attempts"
    }
}

function Invoke-ProcessWithOutput {
    <#
    .SYNOPSIS
    Executes a process and captures its output with timeout handling.
    
    .PARAMETER FilePath
    Path to the executable.
    
    .PARAMETER ArgumentList
    Array of arguments to pass to the executable.
    
    .PARAMETER WorkingDirectory
    Working directory for the process.
    
    .PARAMETER TimeoutSeconds
    Process timeout in seconds.
    
    .PARAMETER EnvironmentVariables
    Hashtable of environment variables to set.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$FilePath,
        
        [Parameter(Mandatory = $false)]
        [string[]]$ArgumentList = @(),
        
        [Parameter(Mandatory = $false)]
        [string]$WorkingDirectory = (Get-Location).Path,
        
        [Parameter(Mandatory = $false)]
        [int]$TimeoutSeconds = 600,
        
        [Parameter(Mandatory = $false)]
        [hashtable]$EnvironmentVariables = @{}
    )
    
    $startTime = Get-Date
    $tempStdOut = [System.IO.Path]::GetTempFileName()
    $tempStdErr = [System.IO.Path]::GetTempFileName()
    
    try {
        $processInfo = New-Object System.Diagnostics.ProcessStartInfo
        $processInfo.FileName = $FilePath
        $processInfo.RedirectStandardOutput = $true
        $processInfo.RedirectStandardError = $true
        $processInfo.UseShellExecute = $false
        $processInfo.CreateNoWindow = $true
        $processInfo.WorkingDirectory = $WorkingDirectory
        
        # Add arguments
        if ($ArgumentList.Count -gt 0) {
            $processInfo.Arguments = $ArgumentList -join " "
        }
        
        # Add environment variables
        foreach ($key in $EnvironmentVariables.Keys) {
            $processInfo.EnvironmentVariables[$key] = $EnvironmentVariables[$key]
        }
        
        $process = New-Object System.Diagnostics.Process
        $process.StartInfo = $processInfo
        
        # Start the process
        $started = $process.Start()
        
        if (-not $started) {
            throw "Failed to start process: $FilePath"
        }
        
        # Wait for completion with timeout
        $completed = $process.WaitForExit($TimeoutSeconds * 1000)
        
        if (-not $completed) {
            $process.Kill()
            throw "Process timed out after $TimeoutSeconds seconds"
        }
        
        # Get output
        $stdOut = $process.StandardOutput.ReadToEnd()
        $stdErr = $process.StandardError.ReadToEnd()
        $exitCode = $process.ExitCode
        
        $endTime = Get-Date
        $duration = $endTime - $startTime
        
        return @{
            ExitCode = $exitCode
            StandardOutput = $stdOut
            StandardError = $stdErr
            Duration = $duration
            Success = ($exitCode -eq 0)
            StartTime = $startTime
            EndTime = $endTime
        }
        
    } catch {
        throw "Process execution failed: $($_.Exception.Message)"
    } finally {
        if ($process -and -not $process.HasExited) {
            $process.Kill()
        }
        
        Remove-Item $tempStdOut, $tempStdErr -ErrorAction SilentlyContinue
    }
}

function Get-SystemResources {
    <#
    .SYNOPSIS
    Gets current system resource usage.
    #>
    try {
        $cpu = (Get-WmiObject -Class Win32_Processor | Measure-Object -Property LoadPercentage -Average).Average
        $memory = Get-WmiObject -Class Win32_OperatingSystem
        $memoryUsedPercent = [math]::Round((($memory.TotalVisibleMemorySize - $memory.FreePhysicalMemory) / $memory.TotalVisibleMemorySize) * 100, 2)
        
        $disk = Get-WmiObject -Class Win32_LogicalDisk -Filter "DriveType=3 AND DeviceID='C:'"
        $diskUsedPercent = [math]::Round((($disk.Size - $disk.FreeSpace) / $disk.Size) * 100, 2)
        
        return @{
            CPU = $cpu
            MemoryUsedPercent = $memoryUsedPercent
            MemoryFreeGB = [math]::Round($memory.FreePhysicalMemory / 1MB, 2)
            MemoryTotalGB = [math]::Round($memory.TotalVisibleMemorySize / 1MB, 2)
            DiskUsedPercent = $diskUsedPercent
            DiskFreeGB = [math]::Round($disk.FreeSpace / 1GB, 2)
            DiskTotalGB = [math]::Round($disk.Size / 1GB, 2)
        }
    } catch {
        Write-TestLog "Failed to get system resources: $($_.Exception.Message)" "WARN" "SYSTEM"
        return @{}
    }
}

function Save-TestArtifact {
    <#
    .SYNOPSIS
    Saves a test artifact (file, screenshot, log) for later analysis.
    
    .PARAMETER Path
    Path to the artifact file.
    
    .PARAMETER Type
    Type of artifact: Log, Screenshot, Configuration, Output, etc.
    
    .PARAMETER Description
    Description of the artifact.
    
    .PARAMETER TestName
    Associated test name.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        
        [Parameter(Mandatory = $true)]
        [string]$Type,
        
        [Parameter(Mandatory = $false)]
        [string]$Description = "",
        
        [Parameter(Mandatory = $false)]
        [string]$TestName = "Unknown"
    )
    
    if (Test-Path $Path) {
        $artifactInfo = @{
            Path = $Path
            Type = $Type
            Description = $Description
            TestName = $TestName
            Size = (Get-Item $Path).Length
            Timestamp = Get-Date
        }
        
        $Script:TestArtifacts += $artifactInfo
        Write-TestLog "Artifact saved: $Type - $Path" "DEBUG" "ARTIFACT"
        
        return $artifactInfo
    } else {
        Write-TestLog "Artifact not found: $Path" "WARN" "ARTIFACT"
        return $null
    }
}

function Get-InstallerVersion {
    <#
    .SYNOPSIS
    Extracts version information from the MSI installer.
    
    .PARAMETER InstallerPath
    Path to the MSI installer file.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$InstallerPath
    )
    
    if (-not (Test-Path $InstallerPath)) {
        throw "Installer not found: $InstallerPath"
    }
    
    try {
        # Use Windows Installer COM object to read MSI properties
        $windowsInstaller = New-Object -ComObject WindowsInstaller.Installer
        $database = $windowsInstaller.GetType().InvokeMember("OpenDatabase", "InvokeMethod", $null, $windowsInstaller, @($InstallerPath, 0))
        
        # Query for version information
        $query = "SELECT Value FROM Property WHERE Property = 'ProductVersion'"
        $view = $database.GetType().InvokeMember("OpenView", "InvokeMethod", $null, $database, $query)
        $view.GetType().InvokeMember("Execute", "InvokeMethod", $null, $view, $null)
        
        $record = $view.GetType().InvokeMember("Fetch", "InvokeMethod", $null, $view, $null)
        
        if ($record) {
            $version = $record.GetType().InvokeMember("StringData", "GetProperty", $null, $record, 1)
            return $version
        } else {
            throw "Could not read version from MSI"
        }
        
    } catch {
        Write-TestLog "Failed to read installer version: $($_.Exception.Message)" "WARN" "INSTALLER"
        return "Unknown"
    } finally {
        if ($view) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($view) | Out-Null }
        if ($database) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($database) | Out-Null }
        if ($windowsInstaller) { [System.Runtime.InteropServices.Marshal]::ReleaseComObject($windowsInstaller) | Out-Null }
    }
}

function Test-RegistryKey {
    <#
    .SYNOPSIS
    Tests if a registry key exists and optionally validates its value.
    
    .PARAMETER Path
    Registry path to test.
    
    .PARAMETER Name
    Registry value name to test.
    
    .PARAMETER ExpectedValue
    Expected value to validate against.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Path,
        
        [Parameter(Mandatory = $false)]
        [string]$Name,
        
        [Parameter(Mandatory = $false)]
        [string]$ExpectedValue
    )
    
    try {
        if ($Name) {
            $value = Get-ItemProperty -Path $Path -Name $Name -ErrorAction Stop
            
            if ($ExpectedValue) {
                return ($value.$Name -eq $ExpectedValue)
            } else {
                return ($value.$Name -ne $null)
            }
        } else {
            $key = Get-Item -Path $Path -ErrorAction Stop
            return ($key -ne $null)
        }
    } catch {
        return $false
    }
}

function Initialize-PerformanceMonitoring {
    <#
    .SYNOPSIS
    Initializes performance monitoring for test execution.
    #>
    $Script:TestMetrics = @{
        StartTime = Get-Date
        ResourceSnapshots = @()
        PerformanceCounters = @{}
    }
    
    # Take initial resource snapshot
    $Script:TestMetrics.ResourceSnapshots += @{
        Timestamp = Get-Date
        Resources = Get-SystemResources
        Type = "Initial"
    }
    
    Write-TestLog "Performance monitoring initialized" "DEBUG" "PERF"
}

function Save-PerformanceSnapshot {
    <#
    .SYNOPSIS
    Saves a performance snapshot during test execution.
    
    .PARAMETER Type
    Type of snapshot: Before, After, During, etc.
    
    .PARAMETER Label
    Descriptive label for the snapshot.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$Type,
        
        [Parameter(Mandatory = $false)]
        [string]$Label = ""
    )
    
    if ($Script:TestMetrics) {
        $snapshot = @{
            Timestamp = Get-Date
            Resources = Get-SystemResources
            Type = $Type
            Label = $Label
        }
        
        $Script:TestMetrics.ResourceSnapshots += $snapshot
        Write-TestLog "Performance snapshot saved: $Type $(if($Label){"- $Label"})" "DEBUG" "PERF"
    }
}

function Get-PerformanceReport {
    <#
    .SYNOPSIS
    Generates a performance report from collected metrics.
    #>
    if (-not $Script:TestMetrics -or $Script:TestMetrics.ResourceSnapshots.Count -eq 0) {
        return $null
    }
    
    $snapshots = $Script:TestMetrics.ResourceSnapshots
    $totalDuration = (Get-Date) - $Script:TestMetrics.StartTime
    
    # Calculate resource usage statistics
    $cpuStats = $snapshots | Where-Object { $_.Resources.CPU } | ForEach-Object { $_.Resources.CPU }
    $memoryStats = $snapshots | Where-Object { $_.Resources.MemoryUsedPercent } | ForEach-Object { $_.Resources.MemoryUsedPercent }
    $diskStats = $snapshots | Where-Object { $_.Resources.DiskUsedPercent } | ForEach-Object { $_.Resources.DiskUsedPercent }
    
    return @{
        TotalDuration = $totalDuration
        SnapshotCount = $snapshots.Count
        CPU = @{
            Average = if ($cpuStats) { ($cpuStats | Measure-Object -Average).Average } else { 0 }
            Maximum = if ($cpuStats) { ($cpuStats | Measure-Object -Maximum).Maximum } else { 0 }
            Minimum = if ($cpuStats) { ($cpuStats | Measure-Object -Minimum).Minimum } else { 0 }
        }
        Memory = @{
            Average = if ($memoryStats) { ($memoryStats | Measure-Object -Average).Average } else { 0 }
            Maximum = if ($memoryStats) { ($memoryStats | Measure-Object -Maximum).Maximum } else { 0 }
            Minimum = if ($memoryStats) { ($memoryStats | Measure-Object -Minimum).Minimum } else { 0 }
        }
        Disk = @{
            Average = if ($diskStats) { ($diskStats | Measure-Object -Average).Average } else { 0 }
            Maximum = if ($diskStats) { ($diskStats | Measure-Object -Maximum).Maximum } else { 0 }
            Minimum = if ($diskStats) { ($diskStats | Measure-Object -Minimum).Minimum } else { 0 }
        }
        Snapshots = $snapshots
    }
}

# Export functions for use by test modules
Export-ModuleMember -Function @(
    "Write-TestLog",
    "New-TestResult",
    "Invoke-TestWithTimeout",
    "Test-ServiceRunning",
    "Test-PortListening",
    "Test-HttpEndpoint",
    "Invoke-ProcessWithOutput",
    "Get-SystemResources",
    "Save-TestArtifact",
    "Get-InstallerVersion",
    "Test-RegistryKey",
    "Initialize-PerformanceMonitoring",
    "Save-PerformanceSnapshot",
    "Get-PerformanceReport"
)
