# Vault CI fetch spec for HotM docsite deploy.
env GT_ACCESS_TOKEN ${GT_ACCESS_TOKEN_VAULT_PATH} ${GT_ACCESS_TOKEN_VAULT_FIELD}
keyfile DEPLOY_SSH_KEY_FILE ${DEPLOY_SSH_KEY_VAULT_PATH} ${DEPLOY_SSH_KEY_VAULT_FIELD}
