#!/usr/bin/env bash
set -euo pipefail

# Generate environment configuration files

cd "${INSTALL_DIR}"

# Production .env for docker-compose
ENV_FILE="${INSTALL_DIR}/.env"

if [ -f "${ENV_FILE}" ]; then
  echo ".env already exists, skipping generation (edit manually if needed)"
else
  echo "Generating .env for Docker Compose..."
  cat > "${ENV_FILE}" <<EOF
# HotM Docker Compose Configuration
# Generated by setup installer

# Fortemi API endpoint
FORTEMI_API_URL=${FORTEMI_API_URL}

# UI settings
APP_TITLE=HotM

# Image registry (default: Gitea registry)
HOTM_REGISTRY=git.integrolabs.net/fortemi

# Image version
VERSION=latest

# AI provider keys (optional)
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
OPENAI_API_KEY=${OPENAI_API_KEY}

# WebSocket transport
VITE_DISABLE_WEBSOCKET=false
EOF
  echo ".env created at ${ENV_FILE}"
fi

# UI .env.local for development
UI_ENV="${INSTALL_DIR}/ui/.env.local"
if [ ! -f "${UI_ENV}" ]; then
  echo "Generating ui/.env.local..."
  cat > "${UI_ENV}" <<EOF
VITE_API_BASE_URL=${FORTEMI_API_URL}
VITE_APP_TITLE=HotM
EOF
  echo "ui/.env.local created"
fi

# Ensure data directory exists
mkdir -p "${DATA_DIR}"

echo "Configuration complete."
